### ISSUE TITLE
Image does not show in html

### ISSUE THREAD

**Issue by jasonqi77** [diego04/cmput410-project#14]
I use <img src="{picture}}" /> to display image, but it seems the file is not found, Where is our root path?

"{picture}}" is profile_images/index.jpeg

**Comment by kevindeasis** [comment]
Is the functions in question: def author_post(request), because it looks like         return render(request, 'LandingPage/post.html') is not returning any image or model

Is this the html in question: post.html? im not sure where is the href of image tag you want to be posted or a model being passed to the html?

Also, im certain in  settings.py you should also see the root

**Comment by chongyangye** [comment]
https://www.youtube.com/watch?v=bSvmlu7OoLk&index=15&list=PLEsfXFp6DpzT5veidCTZ1mQriBX0Mu2LF

**Comment by kevindeasis** [comment]
Also https://docs.djangoproject.com/en/1.7/ref/models/fields/
look at the Imagefield
it allows you to use less than 5 lines of codes to upload and display images.
you can find tutorials on it on the web as well, its in the gitter chat

**Comment by chongyangye** [comment]
we fixed this problem, and we will push to master later
