### ISSUE TITLE
Login broke

### ISSUE THREAD

**Issue by kevindeasis** [diego04/cmput410-project#17]
some merges are not tested? the master has a broken post form, specifically the login post

**Comment by kevindeasis** [comment]
specifically try loging in with different users. only username:test password:test can log in the home page

**Comment by kevindeasis** [comment]
After registering and approving im given this:

Reason given for failure:
    CSRF token missing or incorrect.

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function uses RequestContext for the template, instead of Context.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by gmeyer1** [comment]
Login is fixed for admin and works for users that have been created since the author model was added. Old users will need to be removed or updated as they are no longer compatible with the current authentication system.

Not sure what would be causing the CSRF issue and I can't seem to replicate it reliably. Just did some quick research and it appears it could be related to cookies, doubt it's an authentication issue.
